import type { Metadata, Viewport } from "next";
import { Toaster } from "react-hot-toast";
import ReaderAdScript from "@/components/ads/ReaderAdScript";
import AuthProvider from "@/components/layout/AuthProvider";
import BannedGate from "@/components/layout/BannedGate";
import BetaFeedback from "@/components/layout/BetaFeedback";
import ErrorBoundary from "@/components/layout/ErrorBoundary";
import InstallPrompt from "@/components/layout/InstallPrompt";
import MaintenanceGate from "@/components/layout/MaintenanceGate";
import NotificationPrompt from "@/components/layout/NotificationPrompt";
import Preloader from "@/components/layout/Preloader";
import ServiceWorkerRegister from "@/components/layout/ServiceWorkerRegister";
import SiteChrome from "@/components/layout/SiteChrome";
import { FeedAudioProvider } from "@/lib/audioContext";
import "./globals.css";

// viewportFit: "cover" lets the page draw under the notch/home-indicator so
// env(safe-area-inset-*) resolves to a real value instead of 0 — needed for the mobile
// reader's bottom tab bar padding to actually clear the home indicator on real iOS devices.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#c4622d",
};

export const metadata: Metadata = {
  title: { default: "ÍléOtaku — Africa's Manga Home", template: "%s — ÍléOtaku" },
  description:
    "Discover African manga, manhwa and original creator stories. Read free, go Platinum, or become a creator. Born from the Motherland.",
  keywords: [
    "manga",
    "manhwa",
    "african manga",
    "african comics",
    "webtoon",
    "otaku",
    "reading",
    "comics",
    "ileotaku",
  ],
  authors: [{ name: "ÍléOtaku" }],
  creator: "ÍléOtaku",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://ileotaku.vercel.app",
    siteName: "ÍléOtaku",
    title: "ÍléOtaku — Africa's Manga Home",
    description:
      "African original manga, manhwa and prose stories. Born from the Motherland.",
  },
  twitter: {
    card: "summary_large_image",
    title: "ÍléOtaku — Africa's Manga Home",
    description: "African original manga, manhwa and prose stories.",
    creator: "@ileotaku",
  },
  robots: { index: true, follow: true },
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL ?? "https://ileotaku.vercel.app"),
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "ÍléOtaku",
  },
  // Every size generated by scripts/generate-favicons.js from public/icon.png. `icons.apple`
  // is what actually renders the <link rel="apple-touch-icon"> tag (Next's Metadata API has no
  // literal <meta> equivalent for this — apple-touch-icon has always been a <link>, never a
  // <meta>, so this is the correct, idiomatic way to add it rather than hand-writing one).
  icons: {
    icon: [
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-72.png", sizes: "72x72", type: "image/png" },
      { url: "/icons/icon-96.png", sizes: "96x96", type: "image/png" },
      { url: "/icons/icon-128.png", sizes: "128x128", type: "image/png" },
      { url: "/icons/icon-144.png", sizes: "144x144", type: "image/png" },
      { url: "/icons/icon-152.png", sizes: "152x152", type: "image/png" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-384.png", sizes: "384x384", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
    apple: "/icons/icon-192.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-bg font-noto text-text antialiased">
        <Preloader />
        <ErrorBoundary>
          <AuthProvider>
            <BetaFeedback />
            <FeedAudioProvider>
              <MaintenanceGate>
                <BannedGate>
                  <SiteChrome>{children}</SiteChrome>
                </BannedGate>
              </MaintenanceGate>
              <InstallPrompt />
              <NotificationPrompt />
            </FeedAudioProvider>
          </AuthProvider>
        </ErrorBoundary>
        <ReaderAdScript />
        <ServiceWorkerRegister />
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              background: "#1a1510",
              color: "#e8ddd0",
              border: "1px solid #2a2218",
            },
          }}
        />
      </body>
    </html>
  );
}
